# Generated by Django 3.2.8 on 2021-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=13)),
                ('email', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
